sudo: false
language: node_js
node_js:
- v6
deploy:
  provider: heroku
  api_key:
    secure: NM4SoMufP06v7CQDkJs0ckFwEvufpI95Ly0PG+GEYdCtMWaIV+j1JVjCXUiraOciKwupUpt4LBzejEreO5vF4kSsYdEikQ11Dl8KTmCM8t6WRMZwfKmUsPhRrvt5+h9Jjc+P0Id1/KTNBaOa4E8feBsGkQdKqru+KyRnsJqez1yVXEDrdvxJTwRfJqvRG4E/+U7Jw7TWrsgsAuY5mVJXNNArIjl2YKz5yGd+bkAKnhnzchKkeJn4VMTIWbdnM/muzVuEhnImJVjDR1wqPeR0EWabw/ehp4k85bW+bMJn75SRl3d6Fh/sCjrgHDKfatJRVBNvEQSv1e9uKjc2BbFk+LhBMBk0hmvfEHK3+uGdm71dsuyTkdmaXE9zNRRjMV0UZ9suWdAfKbgWbG1Vnvimf7jeuchZmGLaacsFmdLYgby+MEskM6dAYLU+4bsyKYnz2IoO7qGQrsbWx3hNSHIWmOE+01hL0mIbN3lhf4CseTohhRrpMilJ9EIl0r/4G8veP8Zp4bJETjeQNY7eN/PMTbI4hP6NzTSJUUiSHmmBar9ENflQ08pzdbfiA9bF07N45E4N/OWXnqbxmoWHDW2vHImbOv80a6+jM3xUY6bt/oZa2OP2KDOlM6pZ2X+CulYqf+/R1unCc8Fpg8D+ivcJ1L72OFnGtXDiq4zatBUHt0k=
